### ISSUE TITLE
Fatal error when using -o with file extension in Powershell

### ISSUE THREAD

**Issue by sulliventc** [dasm-assembler/dasm#28]
Using a file extension with the `-o` option in Windows 10 Powershell returns a fatal error.
Example:
`dasm cleanmem.asm -f3 -v0 -ocart.bin` returns `Fatal assembly error: Check command-line format.`

Issue does not exist when `.bin` is omitted, or when dasm is run from command prompt instead.

**Comment by msaarna** [comment]
I was able to confirm this, but the problem seems to be with powershell itself. It's breaking the period+extension off of the filename, into a separate argument.

You can work around it by quoting the filename thusly...

dasm cleanmem.asm -f3 -v0 -o"cart.bin"

...you'll probably have to do the same with any other filename arguments.
