### ISSUE TITLE
SEGFAULT on contrived example

### ISSUE THREAD

**Issue by andrew-davie** [dasm-assembler/dasm#32]
I was trying to learn a bit about how a particular pseudo-op worked, and ended up with a very simple test-case which causes dasm to segfault. I am of the opinion that even if the code is "stupid", dasm should report an error, not crash :)

```
;   segfault

str set ""
str eqm str + "\nAAAAA"
 echo str

; EOF
```

Here's the result...

```
boo@Andrews-MacBook-Pro Chess % ../dasm/bin/dasm ./test.asm -o./test.bin
zsh: segmentation fault  ../dasm/bin/dasm ./test.asm -o./test.bin
```

**Comment by thomas374b** [comment]
This issue could be closed. It is covered by testcase file `test/segfault.asm`.  The testcases are OK. dasm aborts with proper error message about not supported recursion.  

String concatenation can't be supported in this way since the mnemonic gets evaluated recursively again and again.

To serve the use-case itself a specific concatenation mnemonic should be added to dasm as a new feature
