### ISSUE TITLE
forwarding references

### ISSUE THREAD

**Issue by iddq** [dasm-assembler/dasm#6]
```
                        processor hd6303

                        org     $0

                        jsr     test

test
                        bra     test


```

Can you please help me why is it wrong?

> fwref.asm (7): error: Label mismatch...
>  --> test 0003                  
> 
> Unrecoverable error(s) in pass, aborting assembly!
> Complete.

**Comment by andrew-davie** [comment]
I do not know, but I did try with org $1000 and it assembled.
Perhaps some issue with "zero page" - does the HD6303 even have such a thing?

**Comment by iddq** [comment]
forwarding references doesn't work if the label's address is lower than 0x100

**Comment by andrew-davie** [comment]
> forwarding references doesn't work if the label's address is lower than 0x100

... for HD6303. I tested 6502 and it works fine.

**Comment by andrew-davie** [comment]
The error is in the 'jsr' instruction.
Replace it with a 'jmp' and it assembles OK.

**Comment by andrew-davie** [comment]
I suspect this may be an issue/confusion related to the multiple forms of the HD6303 JSR instruction...

<img width="514" alt="Screen Shot 2019-09-07 at 10 34 16 pm" src="https://user-images.githubusercontent.com/16424075/64474990-c8d6f480-d1bf-11e9-9fcf-2a72fed2ec01.png">

In particular, there is a one-byte form and a two-byte form. With the destination address being one-byte (high byte is zero) then that may lead to confusion in the assembly?

With that in mind, I tried the following, which assembles...

`                      processor hd6303

                        org     $0
                        jsr.w     test
test
                        bra     test`

**Comment by andrew-davie** [comment]
To sum this one up in a nutshell:  JSR instruction has three forms. One is specific to the first page of memory. In the case of a JSR with a forward reference to a label in the first page, the assembler is confused between the two. If the 'jsr' follows the label, the assembler will correctly put the single byte jsr form. If the jsr proceeds the label, the assembler errors-out because of a label mismatch. In particular, where it is expecting an 8-bit label it sees a 16-bit label. The proposed 'solution' gets around the label mismatch error by forcing the long-form instruction to be used in the case where we require a JSR before a label which is in the first page.  If a single-byte JSR is required in this situation, instead use a macro to manually insert the opcode and address.

**Comment by thrust26** [comment]
This is only the top of the iceberg. DASM has problems when addresses change.

E.g. I tried to create a conditional branching macro. So depending on the target address, the code would either be e.g.:
```
  bne label
```
or
```
  beq $skip
  jmp label
$skip
```
But DASM doesn't like that, probably because the code length varies between passes and this affects all following labels.

**Comment by msaarna** [comment]
Thomas, can you provide a small test case for your conditional branch failure?

**Comment by thrust26** [comment]
There you go:
[test.zip](https://github.com/dasm-assembler/dasm/files/3964372/test.zip)

For test 5, it seems that in the first passes, the code is compiled using BNE. But in pass 3 DASM detects that it has to use JMP, which causes the target address to change by +3. And that is not liked by DASM.

**Comment by msaarna** [comment]
Thanks. I'll see if anything can be done.

**Comment by msaarna** [comment]
The original test case appear to work in the current master. It looks like the "[allow labels to shift between multiple passes](https://github.com/dasm-assembler/dasm/commit/0c4e4c5273daffb08530f1481c47cc93db5d1f68#diff-25d902c24283ab8cfbac54dfa101ad31)" update fixed the issue.
