### ISSUE TITLE
Fault in -m implementation

### ISSUE THREAD

**Issue by andrew-davie** [dasm-assembler/dasm#82]
```

    .processor 6502
    ORG $1000


N SET 0
    REPEAT 256
    .byte N
N SET N + 1
    REPEND
```

The above will produce a 256 byte binary.
If the"-m#" flag is used, with # being 1,2,3, or 4, the assembler flags a size error, which is incorrect.

```
test.asm (8): error: Recursion too deep in code segment growing larger (4097) than max. allowed file size (4096)
```

Also, "-m" does not appear to range-check its value.
Probably most options don't -- but perhaps we could start to consider this.
For example, "-m-2" makes no sense, but is accepted, and assembles OK.

**Comment by dionoid** [comment]
@thomas374b Is this something you can have a look at?

**Comment by thomas374b** [comment]
> @thomas374b Is this something you can have a look at?

Yes, I will do.

**Comment by thomas374b** [comment]
The -m switch was not intended to limit the size of the created binary. 

It is a safety-halt to prevent too deep recursion that could not be detected otherwise. Initially I thought 64kB would be enough to have as a fixed barrier but there are users who have architectures with banked memory. So I decided to make it configurable and set the default to 640 kB.

This switch needs to be used only on architectures with more than 10 memory banks.

**Comment by andrew-davie** [comment]
TY. Are you happy for me to use the above text in the manual?

**Comment by thomas374b** [comment]
... only if spelling is correct ... ;-)

**Comment by andrew-davie** [comment]
Now updated via bbc091e40e14fcc4d83c6250d632694e2deb0989
